### ISSUE TITLE
POST?

### ISSUE THREAD

**Issue by sofiane-soufi** [benmerckx/monsoon#10]
Hello,

Is there anyway we can get the POST body parameters ? It doesn't seems to be done :/

Thank you.

**Comment by benmerckx** [comment]
There's some backstory in #5, but I as you noticed I did not get round to handling post data. The raw body is available in `request.body` and needs to read and parsed. Depending on your content-type you could use [tink_querystring](https://github.com/haxetink/tink_querystring) or [tink_multipart](https://github.com/haxetink/tink_multipart) to do the latter.

**Comment by sofiane-soufi** [comment]
Yeah, I figured it out after, thank you ! If you need help for this repo, feel free to contact me sofiane.soufi@mone.ca
