### ISSUE TITLE
Blank html output on nodejs (linux and win)

### ISSUE THREAD

**Issue by cambiata** [benmerckx/monsoon#2]
Hi Ben!

Compiling and running works fine on other targets, but when running nodejs
("nodejs bin/node/index.js 2000", and surfing to "localhost:2000") I get nothing but a 
blank html output. (The server is actually running, tracing "nodejs listening on 2000" in thee terminal.)
Same on linux and windows.
Invalid routes give 404 error, but no matter what valid rout I use: blank output.

**Comment by benmerckx** [comment]
Hi Jonas, nodejs works fine here, so could you show me the code you used?

**Comment by cambiata** [comment]
Hm, just tried the monsoon test example with node on my mac, and there it works as expected!

Same problem on my two win machines, and my Ubuntu Gnome 14.04 - blank output on node.
The header info seems to be right:
content type "plain" for localhost:2000/
content type "json" for localhost:2000/arg/123
but still no output. 
(For localhost:2000/arg/123, Firefox complains "Syntax error: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data" - so obviously it's empty)

(All tested with the monsoon test example.)

**Comment by cambiata** [comment]
Ah! Juraj pointed out that there is a problem with tink_http and older versions of node, resulting in blank output. After upgrading node on my Ubuntu 14.04 Gnome, from 0.10.25 to 5.8.0, monsoon works as expected!

Most likely, it's the same old-node-version problem on my windows machines. Will leave this issue open until confirmed.

**Comment by back2dos** [comment]
Yeah, it has something to do with changes in node's streams. It just so
happens that new versions of express on old versions of node show the same
behavior. If you have serious interest in supporting old node version, do
let me know on the tink_http tracker, otherwise I think we can consider
this done ;)

**Comment by cambiata** [comment]
Just tried on windows, upgrading from 0.10.23 to 5.9.1 - now it works there too!
@back2dos No need for old versions. Done! :-)
