### ISSUE TITLE
Tink_http problem when using hxnodejs 4.0.4?

### ISSUE THREAD

**Issue by cambiata** [benmerckx/monsoon#3]
When using hxnodejs 4.0.4, I get the errors below.
Of course, it's probably an tink_http isssue, but I post it here since I'm not sure how to reproduce it without monsoon...
Works fine when using hxnodejs 4.0.3.

```
/home/jonas/haxelib/tink_http/0,1,2/src/tink/http/Container.hx:34: characters 135-152 : Null<haxe.extern.EitherType<String, Array<String>>> should be tink.http.HeaderValue
/home/jonas/haxelib/tink_http/0,1,2/src/tink/http/Container.hx:34: characters 135-152 : haxe.extern.EitherType<String, Array<String>> should be tink.http.HeaderValue
/home/jonas/haxelib/tink_http/0,1,2/src/tink/http/Container.hx:34: characters 135-152 : For function argument 'value'
```

**Comment by nadako** [comment]
This is most probably related to https://github.com/HaxeFoundation/hxnodejs/commit/fbcb80a586754fcd956abf529aa06790066cf88a

**Comment by cambiata** [comment]
Thanks, Dan! Reported as a tink_http issue, but I leave it open 'til it's sorted out.
